# Generated by Django 2.1.4 on 2018-12-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealnutrients',
            name='nutrients_group',
            field=models.SmallIntegerField(choices=[(1, 'Owoce i warzywa'), (2, 'Mięso'), (3, 'Ryby'), (4, 'Nabiał, jajka')], default=0),
            preserve_default=False,
        ),
    ]
