# Generated by Django 2.1.4 on 2018-12-15 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dietapp', '0002_mealnutrients_nutrients_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealnutrients',
            old_name='saturated_fats',
            new_name='fats',
        ),
        migrations.RenameField(
            model_name='mealnutrients',
            old_name='unsaturated_fat',
            new_name='unsaturated_fats',
        ),
    ]
