# Generated by Django 2.1.4 on 2018-12-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietapp', '0003_auto_20181215_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealnutrients',
            name='carbohydrates',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='mealnutrients',
            name='fats',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='mealnutrients',
            name='kcal',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='mealnutrients',
            name='protein',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='mealnutrients',
            name='unsaturated_fats',
            field=models.CharField(max_length=5),
        ),
    ]
