# Generated by Django 2.1.4 on 2018-12-15 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietapp', '0004_auto_20181215_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealnutrients',
            name='nutrients_group',
            field=models.SmallIntegerField(choices=[(1, 'Owoce i warzywa'), (2, 'Mięso'), (3, 'Ryby'), (4, 'Nabiał, jajka'), (5, 'Produkty zbożowe')]),
        ),
    ]
