# Generated by Django 2.1.4 on 2018-12-15 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dietapp', '0005_auto_20181215_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealnutrients',
            name='unsaturated_fats',
        ),
    ]
