# Generated by Django 2.1.4 on 2018-12-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietapp', '0006_remove_mealnutrients_unsaturated_fats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealnutrients',
            name='nutrients_group',
            field=models.SmallIntegerField(choices=[(1, 'Owoce i warzywa'), (2, 'Mięso'), (3, 'Ryby'), (4, 'Produkty zbożowe, jajka')]),
        ),
    ]
