# Generated by Django 2.1.4 on 2018-12-17 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dietapp', '0007_auto_20181215_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bodymeasure',
            old_name='age',
            new_name='birth_year',
        ),
    ]
