# Generated by Django 2.1.4 on 2018-12-18 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dietapp', '0009_bodymeasure_body_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealrecipe',
            old_name='meal_photo',
            new_name='file',
        ),
    ]
