# Generated by Django 2.1.4 on 2018-12-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietapp', '0010_auto_20181218_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealrecipe',
            name='meal_ingredients',
        ),
        migrations.AddField(
            model_name='mealrecipe',
            name='meal_ingredients',
            field=models.ManyToManyField(to='dietapp.MealNutrients'),
        ),
    ]
