# Generated by Django 2.1.4 on 2018-12-18 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dietapp', '0011_auto_20181218_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealrecipe',
            name='meal_ingredients',
        ),
        migrations.AddField(
            model_name='mealrecipe',
            name='meal_ingredients',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dietapp.MealNutrients'),
            preserve_default=False,
        ),
    ]
