# Generated by Django 2.1.4 on 2018-12-18 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietapp', '0014_auto_20181218_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodymeasure',
            name='body_type',
            field=models.SmallIntegerField(choices=[(1, 'ektomorfik'), (2, 'mezomorfik'), (3, 'endomorfik')], default=False),
        ),
    ]
