# Generated by Django 2.1.4 on 2018-12-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietapp', '0016_auto_20181219_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealrecipe',
            name='meal_preparation_time',
            field=models.IntegerField(),
        ),
    ]
