# Generated by Django 2.1.4 on 2018-12-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietapp', '0017_auto_20181220_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealnutrients',
            name='carbohydrates',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='mealnutrients',
            name='fats',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='mealnutrients',
            name='kcal',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='mealnutrients',
            name='protein',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
