# Generated by Django 2.1.4 on 2018-12-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietapp', '0018_auto_20181220_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealnutrients',
            name='nutrients_group',
            field=models.SmallIntegerField(choices=[(1, 'Owoce i warzywa'), (2, 'Mięso'), (3, 'Ryby'), (4, 'Produkty zbożowe'), (5, 'Jajka'), (6, 'Olej')], default=False),
        ),
    ]
